### ISSUE TITLE
Replace noto sans with smaller font

### ISSUE THREAD

**Issue by tonybolzan** [endroid/qr-code#103]
Apparently used only when label exists
`17M	vendor/endroid/qrcode`
`16M	vendor/endroid/qrcode/assets/noto_sans.otf`

**Comment by endroid** [comment]
Hi @tonybolzan I could not find a smaller font containing also Japanese, Chinese and Korean characters. If you (or anyone else) can provide one, I am happy to replace it.

Thank you.

**Comment by endroid** [comment]
Please let me know if you find a smaller font compatible with above languages. You can always use your own font using the setFontPath method.

**Comment by phulstaert** [comment]
Hi @endroid , I understand your logic and 15MB is nothing these days if it means having a global support.

Just out of interest; the Noto Sans is the [Noto Sans from Google font](https://fonts.google.com/noto/specimen/Noto+Sans), right? Because the ttf files are just shy of 500kb and when I use 'some online ttf to otf convertor', the otf also is about 1 MB.

I have no idea how to test if Chinese and Korean still works (I'm from Belgium, so I'm limited to English, French and Dutch), but you might give it a go?

You can find the ttf and otf files [here](https://drive.google.com/drive/folders/1nEfiSx9T8iYsW9MaUFvxBuKSzrWR75RL?usp=sharing)

**Comment by ankurk91** [comment]
https://github.com/satbyy/go-noto-universal/releases
