### ISSUE TITLE
Can label written in two lines?

### ISSUE THREAD

**Issue by DongDavid** [endroid/qr-code#152]
if label written in one lines and the label is to long. part of label will be hiddened .

1. 1. can I afferent label by array and it will be written in lines the same as the length of array?
2. or can I afferent label by string and system Judgment width by length of string and font-size,auto wrap label?
Are these valuable ？

**Comment by Laurent3170** [comment]
Personally, I have setup a monotype font (same size for all letters otherwise « m » and « i » will not be the same size and will affect length of label), made some test to check which number of letters can be displayed, and in the class I adjust font size against the number of letters. i.e. for 10 letters size 15, for above size 12 (numbers arr just an example, I don’t remember the exact values).
Hope it helps.
