### ISSUE TITLE
Output is an empty image

### ISSUE THREAD

**Issue by JosephShenton** [endroid/qr-code#158]
Hi, i am using the demo code + a small file to test what I am doing.

The code looks like this

```
<?php 
	ini_set('memory_limit','-1');
	ini_set('max_execution_time', 0); //0=NOLIMIT
	ini_set('set_time_limit', 0); //0=NOLIMIT
	error_reporting(E_ALL);
	ini_set('display_errors', 1);

	require "vendor/autoload.php";
	use Endroid\QrCode\QrCode;

	$file_data = file_get_contents('small 1.6mb file');
	$data = base64_encode($file_data);

	$qrCode = new QrCode($data);

	header('Content-Type: '.$qrCode->getContentType());
	echo $qrCode->writeString();
?>
```

However the output is just a blank empty image

<img width="1392" alt="screen shot 2018-03-10 at 11 25 26 am" src="https://user-images.githubusercontent.com/12966231/37235787-c29c7040-2455-11e8-9f2d-c9859b34149e.png">

**Comment by endroid** [comment]
Hi @JosephShenton could you include the file so I can try to reproduce the issue here? Also, have you tried setting the image size and are you using the latest version?

**Comment by JosephShenton** [comment]
Sure
I haven't tried setting the image size and yes latest version from composer.
Here is the file
You'll have to unarchive it since GitHub didn't support the file type. It successfully converts to base64 and I can decode it and get the exact file back but I need to either make one QRCode for the entire file or I need to make a sequence of QR Codes to store up to 10 GB of base64 strings. (I'm making a file storage service based on images and QR Codes can do exactly what I need)
[xd-2.aep.zip](https://github.com/endroid/qr-code/files/1799134/xd-2.aep.zip)

**Comment by endroid** [comment]
@JosephShenton Thank you. When I run your code I see that this is caused by the fact that the internal QR code encoder throws an exception "Data too big" even when I set the error correction to the lowest. In other words you should try a smaller string. I don't know the exact rule / maximum size as I do not use QR codes to store large chunks of data so you could try or maybe ask the creator of the https://github.com/Bacon/BaconQrCode what determines this size.
