### ISSUE TITLE
Error Running Basic usage example

### ISSUE THREAD

**Issue by alaksandarjesus** [endroid/qr-code#178]
I am getting this error when i run Basic Usage Example

Parse error: syntax error, unexpected '?' in C:\xampp\htdocs\qrcodephp\vendor\endroid\qr-code\src\QrCode.php on line 170

My php version is 7.2.11

**Comment by endroid** [comment]
Hi @alaksandarjesus this is not related to the QR code library but to your environment so it is difficult for me to assess the source of the error. The only question mark on that line is the one that indicates the optional return type, which is officially supported in PHP 7.2.11. Maybe you are running some kind of virtualization where your local and virtualized version... Otherwise you can ask your question in one of the PHP related channels.
