### ISSUE TITLE
Class 'Endroid\QrCode\Response\QrCodeResponse' not found

### ISSUE THREAD

**Issue by markestocapio** [endroid/qr-code#201]
Installed via composer require endroid/qr-code.

I noticed that the Response class was not downloaded. Able to verify why the Response class is missing?

**Comment by endroid** [comment]
Hi @markestocapio what version do you have installed? When I install the latest version (3.6.0) using composer the QrCodeResponse class is available and the required Symfony\Component\HttpFoundation\Response class also. Can you verify in your file system that the file exists (otherwise something went wrong during composer command and you should delete the vendor/endroid/qr-code directory and reinstall) and the symfony/http-foundation package is installed?

**Comment by markestocapio** [comment]
Hi @endroid,

Earlier I was using PHP 5.6 and the version installed was 2.5. After using PHP 7.2, I managed to install 3.6.0. All are ok now.
