### ISSUE TITLE
Caching qr or output it into file?

### ISSUE THREAD

**Issue by nimasdj** [endroid/qr-code#221]
Instead of generating the same qr each time on fly. Does caching it in file make sense for higher speed? If yes, file cache is better or just use the built-in writeFile method?

**Comment by endroid** [comment]
Hi @nimasdj generating the code and generating an image can be resource consuming, depending on whether you have validation enabled and what output format you use. The standard result format (PNG or SVG) should be very small, so if you have to generate the exact same QR code very often you are better off caching. If the generated QR codes are mainly different, I think you are better off generating live instead of filling your cache :)
