### ISSUE TITLE
Wrong SVG size

### ISSUE THREAD

**Issue by do-web** [endroid/qr-code#222]
The svg have always margin if the svg code are longer then 250 chars.

**Comment by endroid** [comment]
Hi @do-web this is caused by the fact that by default block sizes are rounded to whole numbers which implies a resulting margin. For a PNG this is always the proper behavior, but for scalable formats this is not necessary. However some people like consistent behavior between formats and other like to specify this per format.

You can use the following method to disable block size rounding.
```
$qrCode->setRoundBlockSize(false);
```
