### ISSUE TITLE
Allow (or document) use of library without noto_sans.otf

### ISSUE THREAD

**Issue by crossan007** [endroid/qr-code#224]
The file `noto_sans.otf` is nearly 16MB, which is rather large for a feature that may not be necessary.

I haven't yet investigated, but I imagine it should be possible to generate QR codes (without labels) without including a 16MB otf file in vendor code.

I'll play around with things on my side and update this issue accordingly.

**Comment by endroid** [comment]
Hi @crossan007 thank you. The current font was chosen because it supports Japanese and Chinese I think and dropping that support would cause a BC break for people using the current font so I think it is better to leave it in. But I think your point is valid, a smaller default file would be nicer. I will create an issue for the following major release.

**Comment by crossan007** [comment]
I haven't yet taken a look at the code paths to know whether omitting the font from the build would throw an exception _if a text label is never printed_, so there's that too.
