### ISSUE TITLE
Generate jpeg or jpg image

### ISSUE THREAD

**Issue by irwanagaos** [endroid/qr-code#232]
Is there any option to generate image in another format like jpg or jpeg?

**Comment by endroid** [comment]
Hi @irwanagaos at the moment there is not. Mainly because PNG and SVG are many times more efficient in terms of memory and JPG files are less readable because of the artifacts. In other words there is no real advantage in using the JPG format. If you still like to output the QR code as JPG you can simply convert the PNG image output using the imagecreatefromstring and imagejpeg methods or register your own writer. Whatever suits you best ;)

Good luck!
