### ISSUE TITLE
Adding logo, hides part of the qr code

### ISSUE THREAD

**Issue by syntaxgirl** [endroid/qr-code#339]
When I add logo, it hides the middle part of the qr code. Is there a way to handle this?

**Comment by janssens** [comment]
Same here, I'll look for a workaround

**Comment by janssens** [comment]
The way it works for me is setting a high level of correction and having a small logo.

**Comment by endroid** [comment]
Hi @syntaxgirl the logo indeed overlaps part of the QR code. What exactly is your expected behavior?

**Comment by mstnorris** [comment]
@syntaxgirl it shouldn't be an issue to add an image.logo that obscures part of the QR code due to error correction. See https://en.wikipedia.org/wiki/QR_code#Error_correction

You can check out https://fussyfork.com and the QR codes we generate with our logo in the middle and they scan just fine.

I'd be happy to share the calculation we're using to adjust the size so that the logo sits neatly in the middle without overlapping a portion of a block should that be useful to you?
