### ISSUE TITLE
Replace default font with smaller one

### ISSUE THREAD

**Issue by pveiga2** [endroid/qr-code#383]
First of all, thank you for this great work!
I'd like to suggest a size optimization.

While inspecting through the sources, I noticed the NotoSans Font is only used as a fallback for the Label component.
Out of the approximately 16.8 MB the endroid/qr-code  takes, 16MB alone are due to this font file.

I think this is a bit too much, considering that :
- Labels might not be the most common use-case?
- Labels don't seem to work on SVG.
- Custom Fonts can easily be configured through a FontInterface implementation.

Suggestions: 
- Changing the fallback font to something smaller, like the open_sans.ttf ;
- Skip including the NotoSans file entirely;
- Maybe NotoSans could become a suggested package and, if detected, could then become the default font;

Thank you for your time ;)

**Comment by endroid** [comment]
Hi @pveiga2 I completely agree. Unfortunately I'm stuck with this font in this major version because removing it or replacing it with a font that has a smaller character set would be a BC break that impacts many users. I will keep this issue open for the next major so we don't forget.

In the meantime if anyone has any suggestions for fonts with a high character set vs. small file size ratio, please post them here. As a reference: the current default font is "Noto Sans CJK JP", contains 65535 characters and is 16.4MB. The extra font I provide "Open Sans" contains 938 characters and is 217.4kB. I need something that covers most use cases but has an acceptable small file size.

**Comment by kevinpapst** [comment]
Considering the [amount of daily installations](https://packagist.org/packages/endroid/qr-code/stats) of your package, the proposed changes could make a huge difference in the necessary "computing footprint". 

I wonder how many percent of generated QR codes have labels and how any of those have UTF-8 character?

Maybe it is enough to add a small check:
- if a label character is outside the ascii range 
- throw an exception if setFont() was not called before?

Combined with the idea of @pveiga2 to have a new suggested composer package, re-defining the default font, the BC impact should be rather small for a new major version.

**Comment by kevincerro** [comment]
Any improvement here?

We need to reduce our vendor size and encountered that endroid qr-code size is 16,8MB due fonts

**Comment by endroid** [comment]
No unfortunately not

**Comment by kevinpapst** [comment]
@endroid Does that mean you do not consider this change? 

Last month alone this package was installed 1.1 million times. The sheer amount of computing resources that could be saved, docker image sizes, Github CI caches ... all that for a feature that is likely not required by many people would be a nice win.

**Comment by dkarlovi** [comment]
@kevinpapst you can remove the font via a post-install hook.
https://github.com/liborm85/composer-vendor-cleaner

**Comment by endroid** [comment]
The font is removed in the latest version.

**Comment by kevinpapst** [comment]
Thanks @endroid for tackling the issue 👍  

Looking forward for the time I am out of the [50%](https://packagist.org/packages/endroid/qr-code/php-stats) percentile who cannot yet use it, due to the 8.2+ requirement 😁 
<img width="247" alt="Bildschirmfoto 2024-10-22 um 08 36 28" src="https://github.com/user-attachments/assets/4f990b62-2940-43f0-bf1e-0c0388030f06">

**Comment by endroid** [comment]
Too bad, be patient. But I can tell you're not missing out on any new features yet ;)
